language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

#TODO
#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
